#!/usr/bin/env Rscript

# Copyright (C) 2016 Rodrigo Siqueira
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.

# Load CSV file, and return data.frame structure
load_csv_file <- function(path_csv)
{
  data <- read.csv(file=path_csv, skip=1,
                   col.names=c('Percentage','Time'))
  return(data)
}

# Plot csv file generated by ab. Basically, we have the binned data.
# @param graph_name name to save the graph.
# @param event Expect data.frame as a parameter with event data.
plot_mpm_csv_data <- function(graph_name, values_to_plot)
{
  keys <- names(values_to_plot)
  total_elements_to_plot <- length(values_to_plot)
  set_of_data <- c()

  limit_on_x <- 0
  for (key in keys)
  {
    loaded_file <- load_csv_file(values_to_plot[[key]])
    limit_on_x <- max(loaded_file$Time, limit_on_x)
    set_of_data[[key]] <- loaded_file
  }

  range_x <- c(0, limit_on_x)
  xlabel <- 'Average Response Time (ms)'
  ylabel <- 'Percentage'
  colors <- c('blue', 'green', 'red', 'orange', 'black', 'grey', 'navy')
  selected_colors <- c()
  legend_lty <- c()
  legend_lwd <- c()
  color_index <- 1
  # Build label
  for (color_index in seq(1, total_elements_to_plot))
  {
    selected_colors[color_index] <- colors[color_index]
    legend_lty[color_index] <- 1
    legend_lwd[color_index] <- 2.5
    color_index <- color_index + 1
  }

  margin <- c(5.1, 5.1, 2, 9.1)
  png(graph_name, width=1024, height=768)
  par(mar=margin, xpd=TRUE)

  # First plot
  first_data <- set_of_data[[1]]
  plot(first_data$Time, first_data$Percentage, type='l', col=selected_colors[1],
        ylab=ylabel, xlab=xlabel, xlim=range_x, cex.lab=1.5, lwd=2,
        cex.axis=1.5, cex.main=1.5)
  points(max(first_data$Time), max(first_data$Percentage), pch=3,
         lwd=2)

  # TODO: Workaround
  color_index <- 1
  for (key in keys)
  {
    if (color_index == 1)
    {
      color_index <- color_index + 1
      next
    }
    current_data <- set_of_data[[key]]
    lines(current_data$Time, current_data$Percentage, type='l', col=selected_colors[color_index], lwd=2)
    points(max(current_data$Time), max(current_data$Percentage) , pch=3, lwd=2)
    color_index <- color_index + 1
  }

  # Legend
  legend('topright', inset=c(-0.15,0), legend=keys,
         lty=legend_lty, lwd=legend_lwd, col=selected_colors)
  dev.off()

  return(0)
}

#------------------------------------------------------------------------------
# Handling script execution
#------------------------------------------------------------------------------
# Read arguments
pathsArguments <- commandArgs(trailingOnly=TRUE)

# Verify arguments, before start
argumentsLength <- length(pathsArguments)
if (((argumentsLength %% 2) == 0) | (argumentsLength < 3))
{
  message <- 'missing file operand'
  usage <- 'Rscript binned_data.R SAVE_IMAGE LINE_NAME FILE_TO_PLOT ...'
  message <- paste(message, usage, sep='\n')
  stop(message)
} else
{
  index <- 1
  parameters <- c()
  for (name in pathsArguments)
  {
     # Image path to save
     if (index == 1)
     {
        saveTo <- pathsArguments[index]
     }
     # Names are even number
     else if (index %% 2 == 0)
     {
       nameIndex <- pathsArguments[index]
     }
     # Values are odd number
     else
     {
      parameters[[nameIndex]] <- pathsArguments[index]
     }
     index <- index + 1
  }
}

plot_mpm_csv_data(saveTo, parameters)
