#!/usr/bin/env Rscript

# Copyright (C) 2016 Rodrigo Siqueira
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License version 3 as
# published by the Free Software Foundation.
source(file="util/flexible_parameters.R")

# Load CSV file, and return data.frame structure
load_csv_file <- function(path_csv)
{
  if(!file.exists(path_csv))
  {
    stop(paste('File does not exist: ', path_csv))
  }

  data <- read.csv(file=path_csv, skip=1,
                   col.names=c('Percentage','Time'))
  return(data)
}

# Plot csv file generated by ab. Basically, we have the binned data.
# @param graph_name name to save the graph.
# @param values_to_plot list with values to plot (name and path)
plot_mpm_csv_data <- function(graph_name, values_to_plot)
{
  names_line <- names(values_to_plot)
  total_elements <- length(values_to_plot)
  set_of_data <- c()
  colors <- c('blue', 'green', 'red', 'orange', 'black', 'grey', 'navy')
  xlabel <- 'Response Time (ms)'
  ylabel <- 'Percentage'
  limit_on_x <- 0

  # Load data, find max value for X and create label variables
  for (line in names_line)
  {
    loaded_file <- load_csv_file(values_to_plot[[line]])
    limit_on_x <- max(loaded_file$Time, limit_on_x)
    set_of_data[[line]] <- loaded_file
  }

  margin <- c(5.1, 5.1, 2, 9.1)
  png(graph_name, width=1024, height=768)
  par(mar=margin, xpd=TRUE)

  # First plot
  first_line <- set_of_data[[1]]
  range_x <- c(0, limit_on_x)
  plot(first_line$Time, first_line$Percentage, type='l', col=colors[1],
       ylab=ylabel, xlab=xlabel, xlim=range_x, cex.lab=1.5, lwd=2,
       cex.axis=1.5, cex.main=1.5)
  points(max(first_line$Time), max(first_line$Percentage), pch=3, lwd=2)

  # First element is ignored because of first plot
  color_index <- 2
  names_line <- tail(names_line, n=length(names_line) - 1)
  for (key in names_line)
  {
    current_data <- set_of_data[[key]]
    lines(current_data$Time, current_data$Percentage, type='l',
          col=colors[color_index], lwd=2)
    points(max(current_data$Time), max(current_data$Percentage) , pch=3, lwd=2)
    color_index <- color_index + 1
  }

  # Legend
  par(mar=c(0, 0, 0, 0))
  plot.new()
  legend_color <- head(colors, n=total_elements)
  legend_lty <- rep(1, total_elements)
  legend_lwd <- rep(2.5, total_elements)
  legend('center', 'groups', legend=names(values_to_plot),
         lty=legend_lty, lwd=legend_lwd, col=legend_color, ncol=total_elements,
         bty='n')
  dev.off()

  return(0)
}

plot_mpm_csv_data(save_to, parameters)
